
development:
  adapter: postgresql
  encoding: unicode
  database: cheftab_development
  pool: 5
  username: mvplaptop
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: db/cheftab_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: db/cheftab_production
  pool: 5
  timeout: 5000